# Generated by Django 3.2.5 on 2021-07-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AwardsApp', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
