# Generated by Django 3.2.5 on 2021-07-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwardsApp', '0005_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='profile/'),
        ),
    ]
