# Generated by Django 3.2.5 on 2021-07-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwardsApp', '0005_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
